config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: "registrations" }
  resources :events
  resources :users
  resources :attendances, only: [:create, :destroy, :update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "events#index"
  authenticated :user do
    root to: "users#show", as: :authenticated_root
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
    enum status: { invite_sent: 0, attending: 1 }

    belongs_to :attendee, class_name: "User"
    belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord
    belongs_to :creator, class_name: 'User', foreign_key: 'creator_id'
    has_many :attendances
    has_many :attendees, through: :attendances, source: :user

    scope :upcoming, -> { where('event_end_date >= ?', Date.today) }
    scope :past, -> { where('event_end_date < ?', Date.today) }

    validates :theme, :venue, :details, presence: true
    validates :event_start_date, :event_end_date, presence: true
    validates :event_start_time, :event_end_time, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :own_events, inverse_of: "creator", foreign_key: :creator_id, class_name: "Event"
  has_many :attendances, foreign_key: :attendee_id, inverse_of: "attendee"
  has_many :attended_events, through: :attendances, source: :event
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
    before_action :authenticate_user!, only: [:show]

  def create
      event = Event.find(params[:event_id])
      attendance = Attendance.new(event_id: event.id, attendee_id: params[:attendee_id])

      if attendance.save
          attendance.invite_sent!
          flash[:notice] = "Invited successfully"
          redirect_to users_path(event_id: event.id)
      else
          flash[:alert] = "Something went wrong! contact event owner"
          redirect_to event_path(event)
      end
  end

  def destroy
    event = Event.find(params[:event_id])
    attendance = Attendance.find(params[:id])
    if current_user == event.creator
        attendance.destroy
        flash[:notice] = "The invitation is cancelled!"
    else
        attendance.invite_sent!
        flash[:notice] = "You have earlier indicated to attend #{event.theme} what has changed?"
    end

    if current_user == event.creator
      redirect_to users_path(event_id: event.id, id: attendance.id)
    else
      redirect_to event_path(event)
    end
  end

  def update
    @event = Event.find(params[:event_id])
    @attendance = Attendance.find_by(event_id: params[:event_id], attendee: current_user.id)
    if @attendance && @attendance.invite_sent?
      @attendance.attending!
      flash[:notice] = "Thank you for signing up for the #{@event.theme}"
    else
      flash[:alert] = 'Your name is not on the invitation list'
    end

    redirect_to event_path(@event)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index]

  # GET /events or /events.json
  def index
    @events = Event.all.order("created_at DESC")
  end

  # GET /events/1 or /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events or /events.json
  def create
    @event = current_user.own_events.build(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: "Event was successfully created." }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: "Event was successfully updated." }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: "Event was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:theme, :venue, :details, :event_start_date, :event_end_date, :event_start_time, :event_end_time)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
    private
    def sign_up_params
        params.require(:user).permit(:name, :username, :email, :phone_number, :password, :pass_confirmation)
    end

    def account_update_params
        params.require(:user).permit(:name, :username, :email, :phone_number, :password, :pass_confirmation, :current_password)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!, only: [:show]

    def index 
        @users = User.all
    end

    def show
        @user = current_user
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
    
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/attendances/create.erb
<h2>Attendances#create</h2>

<p>Fine me in app/views/attendances/create.html.erb</p>

app/views/attendances/destroy.html.erb
<h2>Attendances#destroy/h2>

<p>Fine me in app/views/attendances/destroy.html.erb</p>

app/views/events/_event_attendees.html.erb
<div class="column is-one-quarter">
    <nav class="panel">
        <p class="panel-heading">Attendees</p>
        <% User.find(@event.attendances.attending.map {|attended| attended.attendee_id}).each do |attendance| %>
                <p class="panel-block"><%= attendance.name %></p>
        <% end %>
    </nav>
</div>

app/views/events/_event_details.html.erb
<div class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-9">
      <h1 class="title is-4"><%= @event.theme %></h1>
      <p><%= '@' + @event.venue %></p><br />
      <p><%= @event.details %></p><br />

      <p><small><%= "Start date: " + @event.event_start_date.strftime("%a, %b %-d, %Y") %></small></p>

      <p><small><%= "End date: " + @event.event_end_date.strftime("%a, %b %-d, %Y") %></small></p>

      <p><small><%= "Start time: " + @event.event_start_time.strftime("%I:%M %P") %></small></p>

      <p><strong><%= "End time: " + @event.event_end_time.strftime("%I:%M %P") %></strong></p>
      <br />
      
      <% if @event.creator == current_user %>
          <%= button_to "Invite", users_path, params: {:event_id => @event.id}, method: :get, class: "button is-info is-outlined is-fullwidth" %>
      <% else %>
        <% attendance = Attendance.find_by(event_id: @event.id, attendee_id: current_user.id) %>
        <% if attendance && attendance.attending? %>
          <%= button_to "Cancel attendance request to this event", attendance_path(id: attendance.id, event_id: @event.id, attendee_id: current_user.id), method: :delete, class: "button is-info is-outlined is-fullwidth" %>
        <%# elsif attendance.attended_events.past %>
          <%# link_to "This event is closed", user_path(event_id: @event.id, attendee_id: current_user.id) %>
        <% else %>
          <%= button_to "Attend event", attendance_path(event_id: @event.id), method: :patch, class: "button is-info is-outlined is-fullwidth" %>
        <% end %>
      <% end %>
      <br />
    
      <% if current_user == @event.creator %>
        <%= link_to 'Edit', edit_event_path(@event), class: "button is-info is-outlined is-medium"%>
      <% end %>
      <%= link_to 'Back', events_path, class: "button is-info is-outlined is-medium" %> 
    </div>
  </div>
</div>

app/views/events/_form.html.erb
<%= simple_form_for(@event) do |f| %>
  <%= f.error_notification %>
  <div class="field">
    <div class="control">
      <%= f.input :theme, autofocus: true, input_html: {class: "input"}, wrapper: false, label_html: {class: "label"} %>
    </div>
  </div>


  <div class="field">
    <div class="control">
      <%= f.input :venue, input_html: {class: "input"}, wrapper: false, label_html: {class: "label"} %>
    </div>
  </div>

  <div class="field">
    <div class="control">
      <%= f.input :details, input_html: {class: "textarea"}, wrapper: false, label_html: {class: "label"} %>
    </div>
  </div>


  <div class="field">
    <div class="control" id="fcontrol">
      <span>
        <%= f.label :'Start date' %><br />
        <%= f.date_field :event_start_date, input_html: {class: "input"}, wrapper: false, label_html: {class: 'label'} %>
      </span>
      <span>
        <%= f.label :'End date' %><br />
        <%= f.date_field :event_end_date, input_html: {class: "inpu"}, wrapper: false, label_html: {class: 'label'} %>
      </span>
    </div>
  </div>

  <div class="field">
    <div class="control" id="fcontrol">
      <span>
        <%= f.label :'Start time' %><br />
        <%= f.time_field :event_start_time, input_html: {class: "input"} %>
      </span>
      <span class="time-field">
        <%= f.label :'End time' %><br />
        <%= f.time_field :event_end_time, input_html: {class: "input"} %>
      </span>
    </div>
  </div>

  <div class="field">
    <div class="control">
      <%= f.button :submit, class: "button is-success is-outlined" %>
    </div>
  </div>
<% end %>

app/views/events/edit.html.erb
<div class="section">
    <div class="container">
        <div class="columns is-centered">
            <div class="column is-4">
                <h1 class="title is-4">Editing Event</h1>

        <%= render 'form', event: @event %>

        <%= link_to 'Show', @event %> |
        <%= link_to 'Back', events_path %>
    </div>
</div>

app/views/events/index.html.erb
<div id="notice"><%= notice %></div>
<div class="media is-fullwidth">
  <figure class="image is-4by4" id="image">
   <%= image_tag('img/hero-bg.jpg')%>
  </figure>
</div>
<div class="banner-text">
    <h1 class="title is-5" style="font-size:5rem; color:white">
    Events
    </h1>
    <p style="font-size:1.5rem; color:white">
      Events management made easy! <br />Have your target audience, friends
      and <br />loved ones, invited to your events in <br />a more secured way.
      No spamming  <br />in any form. <%= link_to "Sign up today", new_user_registration_path, class: "button is-info is-outlined" %> 
    </p>
  </div>
<div class="section" id="section">
  <div class="container">
    <div class="columns">
      <div class="column" id="column">
        <% @events.each do |event| %>
          <div class="card">
            <div class="card-image">
              <figure class="image is-4by3">
                <%= image_tag('img/events.jpg')%>
              </figure>
            </div>
            <div class="card-header">
              <p class="card-header-title has-text-centered">
                <i class="fa fa-map-marker" aria-hidden="true"></i>
                <span><%= + event.venue %></span>
              </p>
            </div>
            <div class="card-content">
              <div class="content">
                <i><p class="theme"><%= event.theme%></p></i><br />
                <p class="details"><%= link_to event.details.truncate_words(20), event_path(event) %></p><br />
                <i class="fa fa-calendar" aria-hidden="true"></i>
                <span class="event-info"><%= event.event_start_date.strftime('%a. %b %-d, %Y') %></span> -
                <span class="event-info"><%= event.event_end_date.strftime('%a. %b %-d, %Y') %></span><br /> 
                <i class="fa fa-clock-o" aria-hidden="true"></i>
                <span class="event-info"><%= event.event_start_time.strftime("%I:%M %P") %></span> -
                <span class="event-info"><%= event.event_end_time.strftime("%I:%M %P") %></span>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
        

app/views/events/new.html.erb
<div class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-4">
        <h2 class="title is-4">New event</h2>
    <%= render 'form', event: @event %>
    <%= link_to 'Back', events_path %>
    </div>
</div>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>
<section class="section">
  <div class="container">
    <div class="columns">
      <%= render "event_attendees" %>
      <%= render "event_details" %>
    </div>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="notification is-primary global-notification">
        <%= notice %>
      </div>
    <% end %>

    <% if flash[:alert] %>
      <div class="notification is-primary global-notification">
        <%= alert %>
      </div>
    <% end %>

    <nav class="navbar is-white ">
      <div class="navbar-brand is-white">
        <h1 class="title is-5">PrivateEvents</h1>
      </div>

      <div class="navbar-end is-mobile">
        <div class="navbar-burger burger" data-target="navbarExample">
          <span></span>
          <span></span>
          <span></span>
          <span></span>
          <span></span>
      </div>

      <div id="navbarExample" class="navbar-menu">
        <%= link_to "Home", root_path, class: "button is-white" %>
        <% if user_signed_in? %>
          <%= link_to "My events", user_path(current_user.id), class: "button is-white" %>
          <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "button is-warning" %>
          <%= link_to "Creat new event", new_event_path, class: "button is-white" %>
        <% end %>
        
        <% unless user_signed_in? %>
          <%= link_to "Sign In", new_user_session_path, class: "button is-white" %>
          <%= link_to "Sign Up", new_user_registration_path, class: "button is-white" %>
        <% end %>
        
      </div>
    </nav>
    <div class="footer">
      <div class="footer-content">
        <p> Created by Clement Nduonyi for 
        <a href="https://www.theodinproject.com/paths/full-stack-ruby-on-rails/courses/ruby-on-rails">
        theodinproject fullstack Ruby on Rails curiculum ACtiveRecord project</a>
        </p>
        <p>&copy; PrivateEvents 2021</p>
      </div>
    </div>
    <%= yield %>
  </body>
</html>

app/views/users/_attended_events.html.erb
<div class="column is-two-quarter">
    <%= "You have attended " + (@user.attended_events.count).to_s + " event(s)" %>
    <nav class="panel">
        <p class="panel-heading">Attended events</p>
    
        <% if @user.attended_events.empty? %>
            <p class="panel-block"><i>You have not attended any event yet!</i></p>
        <% else %>
            <% @user.attended_events.each do |event| %>
                <p class="panel-block"><%= link_to event.theme, event_path(event) %></p>
            <% end %>
        <% end %>

    </nav>
</div>

app/views/users/_past_events.html.erb
<div class="column is-two-quarter">
    <nav class="panel">
        <p class="panel-heading">Past Events</p>
        <p class="panel-block">
            <% @user.attended_events.past.each do |event| %>
                <%= link_to event.theme, event_path(event) %>
            <% end %>
        </p>
    </nav>
</div>

app/views/users/_upcoming_events.html.erb
<div class="column is-two-quarter">
    <nav class="panel">
        <p class="panel-heading">Upcoming Events</p>
        <% @user.attended_events.upcoming.each do |event| %>
            <p class="panel-block"><%= link_to event.theme, event_path(event) %></p>
        <% end %>
    </nav>
</div>

app/views/users/_user_profile.html.erb
<div class="column is-5 ">
<h1 class="title is-4"><%= (@user.name + "'s" + " Events").upcase %></h1>
    <article class="media">
        <ol class="media-content">
            <% @user.own_events.each do |event| %>
                <li class="content"><%= link_to event.theme, event_path(event) %></li>
            <% end %>

            <%# link_to "Back", root_path %>
        </ol>
    </article>
</div>

app/views/users/index.html.erb
<section class="section">
    <div class=container>
        <div class="columns is-centered">
            <div class="column is-8">
                <div class="box">
                    <h3 class="title is-5 has-text-centered">Possible Invitees</h3>

                <div class="columns is-centered">
                    <table class="table is-half is-hoverable has-text-centered">
                        <tbody>
                            <th class="has-text-centered">Invitee</th>
                            <th class="has-text-centered">Send Invitation</th>
                            <th class="has-text-centered">Attendance status</th>
                            <% event_owner = Event.find(params[:event_id]).creator %>
                            <% @users.reject { |attendee| attendee == event_owner}.each do |attendee| %>
                                <% attendance = Attendance.find_by(event_id: params[:event_id], attendee_id: attendee.id) %>
                                <tr>
                                    <td class="has-text-centered">
                                        <%= attendee.name %>
                                    </td>
                                
                                <% if attendance.nil? %>
                                    <td class="has-text-centered">
                                        <%= button_to "send Invite", attendances_path(event_id: params[:event_id], attendee_id: attendee.id), class: "button is-success is-light" %>
                                    </td>
                                <% else %>

                                    <td class="has-text-centered">
                                        <%= button_to "Cancel invitation", attendance_path(id: attendance.id, event_id: params[:event_id]), method: :delete, class: "button is-warning is-light" %>
                                    </td>
                                <% end %>
                                
                                <% unless attendance.nil? || attendance.status.nil? %>
                                <td class="has-text-centered">
                                    <span class="tag is-primary is-medium is-light"><%= attendance.status %></span>
                                </td>
                                <% else %>
                                    <td></td>
                                <% end %>
                                
                                </tr>
                            <% end %>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</section>            

app/views/users/show.html.erb
<section class="section">
    <div class="container">
        <div class="columns">
            <%= render 'past_events' %>
            <%= render 'user_profile' %>
            <%= render 'attended_events' %>
            <%= render 'upcoming_events' %>
        </div>
   </div>
</section>